# Created using wingetcreate

PackageIdentifier: TabibitoTechnology.Icaros
PackageVersion: 3.2.1.0
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://download1394.mediafire.com/t6sb1toqdbmg/astlvqmkma4zftk/Icaros_v3.2.1.exe
  InstallerSha256: FDC8CB155340378B1F188059D3107F45420F6D7FEA4DDB9C60839CF0A1C278A5
ManifestType: installer
ManifestVersion: 1.0.0
